title: Modify Configuration
status: experimental
description: Modifications to a config that will serve an adversaries impacts or persistance
references:
    - https://attack.mitre.org/techniques/T1100/
    - https://attack.mitre.org/techniques/T1168/
author: Austin Clark
date: 2019/08/12
tags:
    - attack.persistence
    - attack.privilege_escalation
    - attack.t1100
    - attack.t1168
    - attack.t1490
logsource:
    product: cisco
    service: aaa
    category: accounting
fields:
    - CmdSet
detection:
    keywords:
        - 'ip http server'
        - 'ip https server'
        - 'kron policy-list'
        - 'kron occurrence'
        - 'policy-list'
        - 'access-list'
        - 'ip access-group'
        - 'archive maximum'
    condition: keywords
falsepositives:
    - Legitimate administrators may run these commands.
level: medium